### PR TITLE
Update to Latest NIORedis

### PR DESCRIPTION
**Pull request by Mordil**

### CODE REVIEW

**Comment by Mordil** [comment]
Since this is reliant on the open PR https://github.com/mordil/nio-redis/pull/25 , which is missing a commit in that repo's master - this PR is failing CI builds.

Once that PR is merged in NIORedis, then this PR will be updated to rely on master/tagged release which should resolve that issue

**Comment by Mordil** [comment]
@tanner0101 I'm not sure what's causing the build to fail for unit testing - but this PR is ready for review

**Review by tanner0101 — APPROVED** [review]
CI failure was due to old Swift 5 image. I've updated this repo to use the latest official 5.0 image now. 

Changes look great, thanks!

**Comment by penny-coin** [comment]
Hey @Mordil, you just merged a pull request, have a coin! 

You now have 54 coins.

**Pull request merged**
